export const FETCH_UPDATED_BOOKING_SUCCESS = 'FETCH_UPDATED_BOOKING_SUCCESS';
export const FETCH_UPDATED_BOOKING_FAILURE = 'FETCH_UPDATED_BOOKING_FAILURE';

export const FETCH_BOOKING_TIMES = 'FETCH_BOOKING_TIMES';
export const FETCH_BOOKING_TIMES_SUCCESS = 'FETCH_BOOKING_TIMES_SUCCESS';
export const FETCH_BOOKING_TIMES_FAILURE = 'FETCH_BOOKING_TIMES_FAILURE';

export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';