export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const FETCH_UPDATED_BOOKING_SUCCESS = 'FETCH_UPDATED_BOOKING_SUCCESS';
export const FETCH_UPDATED_BOOKING_FAILURE = 'FETCH_UPDATED_BOOKING_FAILURE';
