export const FETCH_UPDATED_BOOKING_SUCCESS = 'FETCH_UPDATED_BOOKING_SUCCESS';
export const FETCH_UPDATED_BOOKING_FAILURE = 'FETCH_UPDATED_BOOKING_FAILURE';

export const FETCH_BOOKING_TIMES_SUCCESS = 'FETCH_BOOKING_TIMES_SUCCESS';
export const FETCH_BOOKING_TIMES_FAILURE = 'FETCH_BOOKING_TIMES_FAILURE';
